[workspace]
authors = ["Damien GUESDON <kisai.dg.slu@gmail.com>"]
channels = ["conda-forge"]
name = "atterrisseur_lunaire"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]
register-kernel = "python -m ipykernel install --user --name atterrisseur_lunaire --display-name \"Eagle-1\""
lab = "jupyter lab notebooks/"
notebook = "jupyter notebook notebooks/"

[dependencies]
python = "3.10.*"
jupyter = "*"
ipykernel = "*"
swig = "*"

[pypi-dependencies]
gymnasium = "*"
stable-baselines3 = "*"
matplotlib = "*"
pygame = "*"
box2d-py = "*"
